"""Canonical event type constants."""

from __future__ import annotations


class EventTypes:
    """Stable event type names used across the platform."""

    KERNEL_BOOTSTRAP_STARTED = "kernel.bootstrap.started"
    KERNEL_BOOTSTRAP_COMPLETED = "kernel.bootstrap.completed"
    KERNEL_SHUTDOWN_STARTED = "kernel.shutdown.started"
    KERNEL_SHUTDOWN_COMPLETED = "kernel.shutdown.completed"
    KERNEL_SUBSYSTEM_STARTED = "kernel.subsystem.started"
    KERNEL_SUBSYSTEM_STOPPED = "kernel.subsystem.stopped"
    KERNEL_SUBSYSTEM_FAILED = "kernel.subsystem.failed"
    CONFIG_LOADED = "config.loaded"
    BUS_STARTED = "events.bus.started"
    BUS_STOPPED = "events.bus.stopped"
    PROVIDER_HEALTH_CHANGED = "provider.health.changed"
    PROVIDER_INVOKED = "provider.invoked"
    PROVIDER_FAILOVER = "provider.failover"
    MISSION_CREATED = "mission.created"
    MISSION_STARTED = "mission.started"
    MISSION_PAUSED = "mission.paused"
    MISSION_RESUMED = "mission.resumed"
    MISSION_CANCELLED = "mission.cancelled"
    MISSION_UPDATED = "mission.updated"
    AGENT_SPAWNED = "agent.spawned"
    AGENT_STARTED = "agent.started"
    AGENT_RETRY = "agent.retry"
    AGENT_VERIFIED = "agent.verified"
    AGENT_TERMINATED = "agent.terminated"
    AGENT_COMPLETED = "agent.completed"
    AGENT_FAILED = "agent.failed"
    MEMORY_WRITTEN = "memory.written"
    MEMORY_RETRIEVED = "memory.retrieved"
    MEMORY_CONSOLIDATED = "memory.consolidated"
    WORLD_UPDATED = "world.updated"
    TOOL_INVOKED = "tool.invoked"
    TOOL_DENIED = "tool.denied"
    TOOL_FAILED = "tool.failed"
    MCP_RELOADED = "mcp.reloaded"
    DESKTOP_LIST_WINDOWS = "desktop.list_windows"
    DESKTOP_FOCUS_WINDOW = "desktop.focus_window"
    DESKTOP_CLIPBOARD_GET = "desktop.clipboard_get"
    DESKTOP_CLIPBOARD_SET = "desktop.clipboard_set"
    DESKTOP_TYPE_TEXT = "desktop.type_text"
    DESKTOP_CLICK = "desktop.click"
    DESKTOP_POWERSHELL = "desktop.powershell"
    DESKTOP_REGISTRY_GET = "desktop.registry_get"
    DESKTOP_REGISTRY_SET = "desktop.registry_set"
    BROWSER_OPEN = "browser.open"
    BROWSER_GOTO = "browser.goto"
    BROWSER_SNAPSHOT = "browser.snapshot"
    BROWSER_CLICK = "browser.click"
    BROWSER_TYPE = "browser.type"
    BROWSER_TABS = "browser.tabs"
    BROWSER_EVAL = "browser.eval"
    BROWSER_CLOSE = "browser.close"
    BROWSER_CDP = "browser.cdp"
    VOICE_SPEAK = "voice.speak"
    VOICE_LISTEN = "voice.listen"
    VOICE_CONVERSE = "voice.converse"
    VOICE_BARGE_IN = "voice.barge_in"
    VOICE_TTS_ROUTE = "voice.tts_route"
    VOICE_SPEECH_PLAN = "voice.speech_plan"
    VOICE_STATE = "voice.state"
